//! On-chain Poseidon, byte-for-byte identical to the circuit's hash.
//!
//! The withdrawal circuit hashes with circomlib's `Poseidon(2)` over BN254. For
//! the contract to maintain its own Merkle tree, rather than trusting an
//! operator-supplied root, it must compute *exactly* the same hash, or a proof
//! generated against the off-chain tree would not verify against the on-chain
//! root.
//!
//! Soroban's `poseidon_permutation` host function is a low-level primitive that
//! takes the MDS matrix and round constants as arguments, so we feed it
//! circomlib's own parameters (see `poseidon_params.rs`, generated by
//! `scripts/gen_poseidon_params.mjs`). Equality with circomlib is not assumed:
//! `test_poseidon_matches_circomlib` checks the output against vectors computed
//! by circomlibjs itself.
//!
//! circomlib's construction for `n` inputs is a permutation over a state of
//! `t = n + 1` field elements, initialised as `[0, inputs...]`, with the hash
//! taken as `state[0]` afterwards.

use soroban_sdk::{symbol_short, vec, Bytes, Env, Symbol, Vec, U256};

use crate::poseidon_params::{D, MDS, ROUNDS_F, ROUNDS_P, ROUND_CONSTANTS, T};

/// The field the permutation operates in, as the host function names it.
const FIELD: Symbol = symbol_short!("BN254");

/// Poseidon parameters marshalled into host objects.
///
/// Building the 65x3 constant table costs a host call per element, so it is
/// built **once** and reused across every hash in a transaction. A Merkle
/// insert performs `LEVELS` hashes; without this the constants would be
/// rebuilt for each one.
pub struct Poseidon {
    mds: Vec<Vec<U256>>,
    round_constants: Vec<Vec<U256>>,
}

impl Poseidon {
    pub fn new(env: &Env) -> Self {
        let mut mds: Vec<Vec<U256>> = Vec::new(env);
        for row in MDS.iter() {
            let mut r: Vec<U256> = Vec::new(env);
            for v in row.iter() {
                r.push_back(u256(env, v));
            }
            mds.push_back(r);
        }
        let mut round_constants: Vec<Vec<U256>> = Vec::new(env);
        for row in ROUND_CONSTANTS.iter() {
            let mut r: Vec<U256> = Vec::new(env);
            for v in row.iter() {
                r.push_back(u256(env, v));
            }
            round_constants.push_back(r);
        }
        Self {
            mds,
            round_constants,
        }
    }

    /// `hash2` over 32-byte field elements, the form Merkle nodes are stored in.
    pub fn hash2_bytes(
        &self,
        env: &Env,
        a: &soroban_sdk::BytesN<32>,
        b: &soroban_sdk::BytesN<32>,
    ) -> soroban_sdk::BytesN<32> {
        let out = self.hash2(
            env,
            &U256::from_be_bytes(env, &Bytes::from_array(env, &a.to_array())),
            &U256::from_be_bytes(env, &Bytes::from_array(env, &b.to_array())),
        );
        out.to_be_bytes()
            .try_into()
            .expect("poseidon output is a 32-byte field element")
    }

    /// circomlib `Poseidon(2)`: permute `[0, a, b]` and take the first element.
    pub fn hash2(&self, env: &Env, a: &U256, b: &U256) -> U256 {
        let state = vec![env, U256::from_u32(env, 0), a.clone(), b.clone()];
        let out = env.crypto_hazmat().poseidon_permutation(
            &state,
            FIELD,
            T,
            D,
            ROUNDS_F,
            ROUNDS_P,
            &self.mds,
            &self.round_constants,
        );
        out.get(0).unwrap()
    }
}

fn u256(env: &Env, bytes: &[u8; 32]) -> U256 {
    U256::from_be_bytes(env, &Bytes::from_array(env, bytes))
}
