//! Verifies a REAL snarkjs Groth16 proof inside the Soroban host environment.
//! The fixture is generated by `scripts/05_export.mjs` from an actual proof,
//! so a passing `cargo test` is genuine on-chain-equivalent ZK verification
//! using the Protocol 26 BN254 pairing host function.

#![cfg(test)]
extern crate std;

use super::*;
use soroban_sdk::{
    testutils::{Address as _, StellarAssetContract},
    token, Address, BytesN, Env, String, Vec,
};

#[path = "fixture.rs"]
mod fixture;

// Parse a hex string into a fixed-size byte array (panics on bad input).
fn hex_to_n<const N: usize>(s: &str) -> [u8; N] {
    let bytes = s.as_bytes();
    assert_eq!(bytes.len(), N * 2, "hex length mismatch");
    let mut out = [0u8; N];
    for i in 0..N {
        out[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
    }
    out
}

fn b64(env: &Env, s: &str) -> BytesN<64> {
    BytesN::from_array(env, &hex_to_n::<64>(s))
}
fn b128(env: &Env, s: &str) -> BytesN<128> {
    BytesN::from_array(env, &hex_to_n::<128>(s))
}
fn b32(env: &Env, s: &str) -> BytesN<32> {
    BytesN::from_array(env, &hex_to_n::<32>(s))
}

fn vk(env: &Env) -> VkBytes {
    let mut ic = Vec::new(env);
    for h in fixture::VK_IC.iter() {
        ic.push_back(b64(env, h));
    }
    VkBytes {
        alpha: b64(env, fixture::VK_ALPHA),
        beta: b128(env, fixture::VK_BETA),
        gamma: b128(env, fixture::VK_GAMMA),
        delta: b128(env, fixture::VK_DELTA),
        ic,
    }
}

fn proof(env: &Env) -> ProofBytes {
    ProofBytes {
        a: b64(env, fixture::PROOF_A),
        b: b128(env, fixture::PROOF_B),
        c: b64(env, fixture::PROOF_C),
    }
}

fn public_inputs(env: &Env) -> Vec<BytesN<32>> {
    let mut v = Vec::new(env);
    for h in fixture::PUBLIC.iter() {
        v.push_back(b32(env, h));
    }
    v
}

/// The on-chain hash must equal the circuit's hash exactly, or a proof built
/// against the off-chain tree would never verify against the on-chain root.
/// Vectors are computed by circomlibjs (see `scripts/gen_poseidon_params.mjs`),
/// so this is a differential test against the real circomlib implementation,
/// not a self-consistency check.
#[test]
fn poseidon_matches_circomlib() {
    let env = Env::default();
    // The permutation is a host function; budget is unlimited in tests but the
    // call still has to be made from inside a contract context.
    let contract_id = env.register(Veil, ());
    env.as_contract(&contract_id, || {
        let p = poseidon::Poseidon::new(&env);
        for (a, b, expected) in poseidon_params::TEST_VECTORS.iter() {
            let out = p.hash2(
                &env,
                &U256::from_be_bytes(&env, &Bytes::from_array(&env, a)),
                &U256::from_be_bytes(&env, &Bytes::from_array(&env, b)),
            );
            let got: [u8; 32] = out
                .to_be_bytes()
                .try_into()
                .expect("hash output is 32 bytes");
            assert_eq!(
                got, *expected,
                "on-chain Poseidon disagrees with circomlib for input pair"
            );
        }
    });
}

/// The contract's incremental tree must produce the same root as the prover's
/// tree in `scripts/lib/veil.mjs` after every insert. If it did not, a proof
/// built against the off-chain tree would name a root the contract never
/// derived, and every honest withdrawal would fail.
///
/// Expected roots come from that exact JS implementation, so this is a
/// differential test across the two, not a restatement of one in the other.
#[test]
fn merkle_tree_matches_prover() {
    let env = Env::default();
    // Inserting five leaves is 100 Poseidon permutations, far more than one
    // transaction ever performs; `deposit_fits_in_transaction_budget` is what
    // holds the real per-deposit cost to account.
    env.cost_estimate().budget().reset_unlimited();
    let contract_id = env.register(Veil, ());
    env.as_contract(&contract_id, || {
        let poseidon = poseidon::Poseidon::new(&env);
        let mut tree = merkle::Tree::empty(&env);

        // An empty tree's root is the empty-subtree root at the top level.
        assert_eq!(
            tree.current_root(),
            BytesN::from_array(&env, &poseidon_params::ZEROS[poseidon_params::LEVELS as usize]),
            "empty tree root mismatch"
        );

        for (i, leaf) in poseidon_params::MERKLE_LEAVES.iter().enumerate() {
            let root = tree.insert(&env, &poseidon, BytesN::from_array(&env, leaf));
            assert_eq!(
                root,
                BytesN::from_array(&env, &poseidon_params::MERKLE_ROOTS[i]),
                "root after insert {} disagrees with the prover's tree",
                i + 1
            );
            assert!(tree.knows_root(&root), "freshly derived root not recognised");
        }

        assert_eq!(tree.next_index, poseidon_params::MERKLE_LEAVES.len() as u32);
    });
}

/// One deposit costs `LEVELS` Poseidon permutations plus the one-off cost of
/// marshalling the constant table. That has to fit inside a single Soroban
/// transaction or the on-chain tree is not deployable, so the cost is measured
/// rather than assumed, and printed so a regression is visible.
#[test]
fn deposit_fits_in_transaction_budget() {
    let env = Env::default();
    let contract_id = env.register(Veil, ());
    env.as_contract(&contract_id, || {
        let poseidon = poseidon::Poseidon::new(&env);
        let mut tree = merkle::Tree::empty(&env);
        tree.insert(
            &env,
            &poseidon,
            BytesN::from_array(&env, &poseidon_params::MERKLE_LEAVES[0]),
        );
    });

    let budget = env.cost_estimate().budget();
    std::println!(
        "one deposit: {} cpu instructions, {} bytes memory",
        budget.cpu_instruction_cost(),
        budget.memory_bytes_cost()
    );
    // Env::default() is configured with the network's per-transaction limits,
    // so completing the insert without a Budget/ExceededLimit error is itself
    // the assertion. This bound just makes a regression loud.
    assert!(
        budget.cpu_instruction_cost() < 100_000_000,
        "a single deposit costs {} cpu instructions",
        budget.cpu_instruction_cost()
    );
}

const DENOM: i128 = 10_0000000;

/// A pool funded with the exact deposits the fixture's proof was built against,
/// so the root the contract derives is the root the proof names.
struct Pool<'a> {
    env: &'a Env,
    client: VeilClient<'a>,
    token: Address,
    asset: StellarAssetContract,
}

fn setup_pool(env: &Env) -> Pool<'_> {
    env.mock_all_auths();
    env.cost_estimate().budget().reset_unlimited();

    let admin = Address::generate(env);
    let asset = env.register_stellar_asset_contract_v2(admin.clone());
    let token = asset.address();

    let contract_id = env.register(Veil, ());
    let client = VeilClient::new(env, &contract_id);
    let auditor = BytesN::from_array(env, &[7u8; 32]);
    client.init(&admin, &token, &DENOM, &auditor, &vk(env));

    // Fund a depositor and make the five deposits the proof assumes.
    let depositor = Address::generate(env);
    token::StellarAssetClient::new(env, &token)
        .mint(&depositor, &(DENOM * fixture::COMMITMENTS.len() as i128));

    let empty_audit = Bytes::new(env);
    for c in fixture::COMMITMENTS.iter() {
        client.deposit(
            &depositor,
            &BytesN::from_array(env, &hex_to_n::<32>(c)),
            &empty_audit,
        );
    }

    // The fixture must describe one run: the proof's root input and the
    // scenario's root have to be the same, or the deposits below reproduce a
    // tree the proof says nothing about. Regenerating only half of the fixture
    // is easy to do by accident (05_export.mjs can be pointed at a proof from a
    // different scenario), and without this it surfaces as an opaque
    // UnknownRoot much later.
    assert_eq!(
        fixture::PUBLIC[0],
        fixture::DEPOSITS_ROOT,
        "fixture.rs is internally inconsistent: the proof's root input is not \
         the scenario's deposits root. Regenerate with `npm run prove` followed \
         by `node scripts/05_export.mjs`."
    );

    // The contract must have arrived at the prover's root on its own.
    assert_eq!(
        client.root(),
        BytesN::from_array(env, &hex_to_n::<32>(fixture::DEPOSITS_ROOT)),
        "contract-derived root does not match the prover's tree"
    );
    client.set_association_root(&BytesN::from_array(
        env,
        &hex_to_n::<32>(fixture::ASSOCIATION_ROOT),
    ));

    Pool {
        env,
        client,
        token,
        asset,
    }
}

impl Pool<'_> {
    fn balance(&self, who: &Address) -> i128 {
        token::TokenClient::new(self.env, &self.token).balance(who)
    }
    fn recipient(&self) -> Address {
        Address::from_string(&String::from_str(self.env, fixture::RECIPIENT))
    }
    fn relayer(&self) -> Address {
        Address::from_string(&String::from_str(self.env, fixture::RELAYER))
    }
}

/// The whole point: a real proof pays exactly the address it committed to, the
/// relayer gets exactly the committed fee, and the note is then spent.
#[test]
fn withdraw_pays_the_committed_addresses() {
    let env = Env::default();
    let pool = setup_pool(&env);
    let recipient = pool.recipient();
    let relayer = pool.relayer();

    pool.client
        .withdraw(&proof(&env), &public_inputs(&env), &recipient, &relayer);

    assert_eq!(
        pool.balance(&recipient),
        DENOM - fixture::FEE,
        "recipient was not paid the note minus the fee"
    );
    assert_eq!(
        pool.balance(&relayer),
        fixture::FEE,
        "relayer was not paid the committed fee"
    );
}

/// The theft vector this work exists to close.
///
/// The proof and its public inputs are lifted verbatim, exactly what a
/// bystander watching the network can do, and resubmitted naming an attacker's
/// address. The proof itself is still perfectly valid, because nothing it
/// commits to has changed. Only the contract's check that the payee is the
/// committed payee stops the funds walking out.
#[test]
fn withdraw_rejects_a_substituted_recipient() {
    let env = Env::default();
    let pool = setup_pool(&env);
    let attacker = Address::generate(&env);

    let err = pool
        .client
        .try_withdraw(
            &proof(&env),
            &public_inputs(&env),
            &attacker,
            &pool.relayer(),
        )
        .expect_err("a redirected withdrawal was accepted");

    assert_eq!(err, Ok(Error::RecipientMismatch));
    assert_eq!(pool.balance(&attacker), 0, "attacker was paid");
    assert_eq!(
        pool.balance(&pool.recipient()),
        0,
        "note was spent despite the failure"
    );
}

/// The same substitution attempted against the relayer slot: a third party
/// cannot steal the relaying fee out of someone else's pending withdrawal.
#[test]
fn withdraw_rejects_a_substituted_relayer() {
    let env = Env::default();
    let pool = setup_pool(&env);
    let attacker = Address::generate(&env);

    let err = pool
        .client
        .try_withdraw(
            &proof(&env),
            &public_inputs(&env),
            &pool.recipient(),
            &attacker,
        )
        .expect_err("a redirected relayer fee was accepted");

    assert_eq!(err, Ok(Error::RelayerMismatch));
    assert_eq!(pool.balance(&attacker), 0, "attacker collected the fee");
}

/// A spent note stays spent. The nullifier is stored under its canonical bytes
/// and the canonical check refuses any other encoding of the same field
/// element, so there is no second spelling of an already-used nullifier.
#[test]
fn withdraw_rejects_a_replayed_note() {
    let env = Env::default();
    let pool = setup_pool(&env);
    let recipient = pool.recipient();
    let relayer = pool.relayer();

    pool.client
        .withdraw(&proof(&env), &public_inputs(&env), &recipient, &relayer);

    // Straight replay.
    let err = pool
        .client
        .try_withdraw(&proof(&env), &public_inputs(&env), &recipient, &relayer)
        .expect_err("a replayed withdrawal was accepted");
    assert_eq!(err, Ok(Error::NullifierAlreadyUsed));

    // A spent note redirected elsewhere reports the binding failure, not the
    // spend, so a caller is told the most specific reason the call was refused.
    let attacker = Address::generate(&env);
    let err = pool
        .client
        .try_withdraw(&proof(&env), &public_inputs(&env), &attacker, &relayer)
        .expect_err("a redirected replay was accepted");
    assert_eq!(err, Ok(Error::RecipientMismatch));

    // Replay under a second encoding of the same nullifier field element.
    let mut pubs = public_inputs(&env);
    let shifted = add_modulus(&hex_to_n::<32>(fixture::PUBLIC[2]));
    pubs.set(2, BytesN::from_array(&env, &shifted));
    let err = pool
        .client
        .try_withdraw(&proof(&env), &pubs, &recipient, &relayer)
        .expect_err("a re-encoded nullifier was accepted");
    assert_eq!(err, Ok(Error::NonCanonicalInput));

    assert_eq!(
        pool.balance(&recipient),
        DENOM - fixture::FEE,
        "note paid out more than once"
    );
}

/// A root the contract never derived must not be usable, which is what stops an
/// operator inventing a tree containing commitments nobody deposited against.
#[test]
fn withdraw_rejects_an_unknown_root() {
    let env = Env::default();
    let pool = setup_pool(&env);

    let mut pubs = public_inputs(&env);
    let mut fake = hex_to_n::<32>(fixture::DEPOSITS_ROOT);
    fake[31] ^= 0x01;
    pubs.set(0, BytesN::from_array(&env, &fake));

    let err = pool
        .client
        .try_withdraw(&proof(&env), &pubs, &pool.recipient(), &pool.relayer())
        .expect_err("an unknown root was accepted");
    assert_eq!(err, Ok(Error::UnknownRoot));
}

/// The contract's address encoding must agree with the prover's, or every
/// honest withdrawal would be rejected as a recipient mismatch. Expected limbs
/// are the output of `addressToLimbs` in scripts/lib/veil.mjs for these two
/// SEP-23 addresses, so this pins the two implementations together.
#[test]
fn address_limbs_match_prover() {
    let env = Env::default();

    // Account address (G...), discriminant 0.
    let account = Address::from_str(&env, "GA7QYNF7SOWQ3GLR2BGMZEHXAVIRZA4KVWLTJJFC7MGXUA74P7UJVSGZ");
    let (hi, lo) = address_bind::to_limbs(&env, &account).expect("account payload");
    assert_eq!(
        hi,
        BytesN::from_array(
            &env,
            &hex_to_n::<32>("000000000000000000000000000000003f0c34bf93ad0d9971d04ccc90f70551")
        ),
        "account high limb"
    );
    assert_eq!(
        lo,
        BytesN::from_array(
            &env,
            &hex_to_n::<32>("000000000000000000000000000000001c838aad9734a4a2fb0d7a03fc7fe89a")
        ),
        "account low limb"
    );

    // Contract address (C...), discriminant 1, must not collide with an
    // account carrying the same 32-byte payload.
    let contract = Address::from_str(&env, "CA3D5KRYM6CB7OWQ6TWYRR3Z4T7GNZLKERYNZGGA5SOAOPIFY6YQGAXE");
    let (chi, clo) = address_bind::to_limbs(&env, &contract).expect("contract payload");
    assert_eq!(
        chi,
        BytesN::from_array(
            &env,
            &hex_to_n::<32>("00000000000000000000000000000001363eaa3867841fbad0f4ed88c779e4fe")
        ),
        "contract high limb"
    );
    assert_eq!(
        clo,
        BytesN::from_array(
            &env,
            &hex_to_n::<32>("0000000000000000000000000000000066e56a2470dc98c0ec9c073d05c7b103")
        ),
        "contract low limb"
    );

    // Both limbs must be canonical field elements by construction.
    for limb in [&hi, &lo, &chi, &clo] {
        assert!(field::is_canonical(limb), "limb is not a canonical field element");
    }
}

/// Add the BN254 scalar field modulus to a 32-byte big-endian value. The result
/// is a *different* byte string that represents the *same* field element.
fn add_modulus(x: &[u8; 32]) -> [u8; 32] {
    // p = 21888242871839275222246405745257275088548364400416034343698204186575808495617
    const P: [u8; 32] = [
        0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29, 0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81, 0x58,
        0x5d, 0x28, 0x33, 0xe8, 0x48, 0x79, 0xb9, 0x70, 0x91, 0x43, 0xe1, 0xf5, 0x93, 0xf0, 0x00,
        0x00, 0x01,
    ];
    let mut out = [0u8; 32];
    let mut carry = 0u16;
    for i in (0..32).rev() {
        let s = x[i] as u16 + P[i] as u16 + carry;
        out[i] = (s & 0xff) as u8;
        carry = s >> 8;
    }
    assert_eq!(carry, 0, "test vector overflowed 32 bytes");
    out
}

/// A non-canonical encoding of a public input must be rejected outright.
///
/// The proof system only ever sees a field element, so `n` and `n + p` are the
/// same input to it. But the contract keys spent notes on the *bytes* of the
/// nullifier hash. If the host silently reduces mod p, a spent note could be
/// withdrawn a second time under the encoding `n + p`: same proof, same field
/// element, different storage key. Rejecting anything at or above the modulus
/// closes that off before the proof is even checked.
#[test]
fn rejects_non_canonical_public_input() {
    let env = Env::default();
    let contract_id = env.register(Veil, ());
    let client = VeilClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    let token = Address::generate(&env);
    let auditor = BytesN::from_array(&env, &[7u8; 32]);
    client.init(&admin, &token, &100_0000000i128, &auditor, &vk(&env));

    let mut pubs = public_inputs(&env);
    let shifted = add_modulus(&hex_to_n::<32>(fixture::PUBLIC[2]));
    pubs.set(2, BytesN::from_array(&env, &shifted));

    assert!(
        !client.verify_proof(&proof(&env), &pubs),
        "a non-canonical public input (n + p) was accepted; spent notes could be \
         replayed under a second encoding"
    );
}

#[test]
fn verifies_real_proof() {
    let env = Env::default();
    let contract_id = env.register(Veil, ());
    let client = VeilClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    let token = Address::generate(&env);
    let auditor = BytesN::from_array(&env, &[7u8; 32]);
    client.init(&admin, &token, &100_0000000i128, &auditor, &vk(&env));

    // The real proof must verify against the host BN254 pairing check.
    let ok = client.verify_proof(&proof(&env), &public_inputs(&env));
    assert!(ok, "real Groth16 proof failed on-chain verification");
}

#[test]
fn rejects_tampered_public_input() {
    let env = Env::default();
    let contract_id = env.register(Veil, ());
    let client = VeilClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    let token = Address::generate(&env);
    let auditor = BytesN::from_array(&env, &[7u8; 32]);
    client.init(&admin, &token, &100_0000000i128, &auditor, &vk(&env));

    // Flip the nullifierHash public input -> proof must now FAIL.
    let mut pubs = public_inputs(&env);
    let mut bad = hex_to_n::<32>(fixture::PUBLIC[2]);
    bad[31] ^= 0x01;
    pubs.set(2, BytesN::from_array(&env, &bad));

    let ok = client.verify_proof(&proof(&env), &pubs);
    assert!(!ok, "tampered public input was wrongly accepted");
}
