//! Verifies a REAL snarkjs Groth16 proof inside the Soroban host environment.
//! The fixture is generated by `scripts/05_export.mjs` from an actual proof —
//! so a passing `cargo test` is genuine on-chain-equivalent ZK verification
//! using the Protocol 26 BN254 pairing host function.

#![cfg(test)]
extern crate std;

use super::*;
use soroban_sdk::{testutils::Address as _, Address, BytesN, Env, Vec};

#[path = "fixture.rs"]
mod fixture;

// Parse a hex string into a fixed-size byte array (panics on bad input).
fn hex_to_n<const N: usize>(s: &str) -> [u8; N] {
    let bytes = s.as_bytes();
    assert_eq!(bytes.len(), N * 2, "hex length mismatch");
    let mut out = [0u8; N];
    for i in 0..N {
        out[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
    }
    out
}

fn b64(env: &Env, s: &str) -> BytesN<64> {
    BytesN::from_array(env, &hex_to_n::<64>(s))
}
fn b128(env: &Env, s: &str) -> BytesN<128> {
    BytesN::from_array(env, &hex_to_n::<128>(s))
}
fn b32(env: &Env, s: &str) -> BytesN<32> {
    BytesN::from_array(env, &hex_to_n::<32>(s))
}

fn vk(env: &Env) -> VkBytes {
    let mut ic = Vec::new(env);
    for h in fixture::VK_IC.iter() {
        ic.push_back(b64(env, h));
    }
    VkBytes {
        alpha: b64(env, fixture::VK_ALPHA),
        beta: b128(env, fixture::VK_BETA),
        gamma: b128(env, fixture::VK_GAMMA),
        delta: b128(env, fixture::VK_DELTA),
        ic,
    }
}

fn proof(env: &Env) -> ProofBytes {
    ProofBytes {
        a: b64(env, fixture::PROOF_A),
        b: b128(env, fixture::PROOF_B),
        c: b64(env, fixture::PROOF_C),
    }
}

fn public_inputs(env: &Env) -> Vec<BytesN<32>> {
    let mut v = Vec::new(env);
    for h in fixture::PUBLIC.iter() {
        v.push_back(b32(env, h));
    }
    v
}

#[test]
fn verifies_real_proof() {
    let env = Env::default();
    let contract_id = env.register(Veil, ());
    let client = VeilClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    let token = Address::generate(&env);
    let auditor = BytesN::from_array(&env, &[7u8; 32]);
    client.init(&admin, &token, &100_0000000i128, &auditor, &vk(&env));

    // The real proof must verify against the host BN254 pairing check.
    let ok = client.verify_proof(&proof(&env), &public_inputs(&env));
    assert!(ok, "real Groth16 proof failed on-chain verification");
}

#[test]
fn rejects_tampered_public_input() {
    let env = Env::default();
    let contract_id = env.register(Veil, ());
    let client = VeilClient::new(&env, &contract_id);

    let admin = Address::generate(&env);
    let token = Address::generate(&env);
    let auditor = BytesN::from_array(&env, &[7u8; 32]);
    client.init(&admin, &token, &100_0000000i128, &auditor, &vk(&env));

    // Flip the nullifierHash public input -> proof must now FAIL.
    let mut pubs = public_inputs(&env);
    let mut bad = hex_to_n::<32>(fixture::PUBLIC[2]);
    bad[31] ^= 0x01;
    pubs.set(2, BytesN::from_array(&env, &bad));

    let ok = client.verify_proof(&proof(&env), &pubs);
    assert!(!ok, "tampered public input was wrongly accepted");
}
