// Convert snarkjs JSON (proof.json / public.json / verification_key.json) into
// the byte layout the Soroban BN254 verifier expects.
//
// Soroban's BN254 points are "Ethereum-compatible" (EIP-197 alt_bn128):
//   G1  = x(32) || y(32)                              -> 64 bytes
//   G2  = x.c1(32) || x.c0(32) || y.c1(32) || y.c0(32) -> 128 bytes
//        NOTE the coefficient SWAP: snarkjs stores Fp2 as [c0, c1] (real
//        first); the Ethereum/Soroban precompile wants the imaginary part
//        first. Getting this wrong is the #1 reason on-chain Groth16 fails.
//   Fr  = 32-byte big-endian scalar.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

process.chdir(resolve(dirname(fileURLToPath(import.meta.url)), ".."));

const P =
  21888242871839275222246405745257275088696311157297823662689037894645226208583n; // Fp modulus

function hex32(dec) {
  let v = BigInt(dec) % (1n << 256n);
  return v.toString(16).padStart(64, "0");
}
// G1: [x, y, "1"] -> 128 hex chars (64 bytes)
function g1(p) {
  return hex32(p[0]) + hex32(p[1]);
}
// G2: [[x0,x1],[y0,y1], ...] -> swap to [x1,x0,y1,y0] -> 256 hex chars (128 bytes)
function g2(p) {
  return hex32(p[0][1]) + hex32(p[0][0]) + hex32(p[1][1]) + hex32(p[1][0]);
}
// Negate a G1 point on the curve: -(x, y) = (x, P - y).
function g1neg(p) {
  const y = BigInt(p[1]) % P;
  const negY = y === 0n ? 0n : P - y;
  return hex32(p[0]) + hex32(negY.toString());
}

const proof = JSON.parse(readFileSync("build/proof.json"));
const pub = JSON.parse(readFileSync("build/public.json"));
const vk = JSON.parse(readFileSync("build/verification_key.json"));

const out = {
  curve: "bn254",
  // proof
  proof: {
    a: g1(proof.pi_a),
    a_neg: g1neg(proof.pi_a), // handy if negation is done off-chain
    b: g2(proof.pi_b),
    c: g1(proof.pi_c),
  },
  // verification key
  vk: {
    alpha: g1(vk.vk_alpha_1),
    beta: g2(vk.vk_beta_2),
    gamma: g2(vk.vk_gamma_2),
    delta: g2(vk.vk_delta_2),
    ic: vk.IC.map(g1),
  },
  // public signals as 32-byte scalars, in circuit order:
  // [root, associationRoot, nullifierHash, recipient, fee]
  publicSignals: pub.map(hex32),
};

writeFileSync("build/soroban_inputs.json", JSON.stringify(out, null, 2));
console.log("✓ Wrote build/soroban_inputs.json");

// Also emit a Rust fixture so the contract's test can verify this exact proof
// in the real Soroban host environment.
const icLines = out.vk.ic.map((h) => `    "${h}",`).join("\n");
const pubLines = out.publicSignals.map((h) => `    "${h}",`).join("\n");
const rust = `// AUTO-GENERATED by scripts/05_export.mjs from a real snarkjs proof.
// Do not edit by hand. Byte layout: EIP-197 (BN254, big-endian).
#![allow(dead_code)]
pub const PROOF_A: &str = "${out.proof.a}";
pub const PROOF_B: &str = "${out.proof.b}";
pub const PROOF_C: &str = "${out.proof.c}";
pub const VK_ALPHA: &str = "${out.vk.alpha}";
pub const VK_BETA: &str = "${out.vk.beta}";
pub const VK_GAMMA: &str = "${out.vk.gamma}";
pub const VK_DELTA: &str = "${out.vk.delta}";
pub const VK_IC: [&str; ${out.vk.ic.length}] = [
${icLines}
];
pub const PUBLIC: [&str; ${out.publicSignals.length}] = [
${pubLines}
];
`;
writeFileSync("contracts/veil/src/fixture.rs", rust);
console.log("✓ Wrote contracts/veil/src/fixture.rs (Rust test fixture)");

console.log("  proof.a  =", out.proof.a.slice(0, 32), "…");
console.log("  IC count =", out.vk.ic.length, "(should be #publicSignals + 1 =", pub.length + 1, ")");
console.log("  public signals:", out.publicSignals.length);
