// Emit circomlib's Poseidon parameters for t=3 (the 2-input hash used by every
// Merkle node) as a Rust source file, plus a set of test vectors.
//
// The on-chain incremental Merkle tree must compute EXACTLY the same hash the
// circuit does, or a proof generated against the off-chain tree will not verify
// against the on-chain root. Rather than trusting that Soroban's generic
// `poseidon_permutation` host function agrees with circomlib, we feed it
// circomlib's own constants and check the outputs match on real vectors.
//
//   node scripts/gen_poseidon_params.mjs
//
// Writes contracts/veil/src/poseidon_params.rs (generated, do not hand-edit).

import { readFileSync, writeFileSync } from "node:fs";
import { buildPoseidon } from "circomlibjs";

// circomlibjs restricts its "exports" map and does not expose the raw constant
// table, so read the shipped JSON straight off disk. These are the same
// constants circomlib's Poseidon circuit is compiled against.
const poseidonConstants = JSON.parse(
  readFileSync("node_modules/circomlibjs/src/poseidon_constants.json", "utf8")
);

// circomlib parameters for BN254, t = 3 (i.e. Poseidon with 2 inputs).
// N_ROUNDS_F is 8 for every t; N_ROUNDS_P is table-indexed by (t - 2).
const T = 3;
const ROUNDS_F = 8;
const ROUNDS_P = [56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68][T - 2];
const IDX = T - 2;

// Constants ship as decimal strings; C is flat (rounds * t), M is t-by-t.
const C = poseidonConstants.C[IDX].map((x) => BigInt(x));
const M = poseidonConstants.M[IDX].map((row) => row.map((x) => BigInt(x)));

if (C.length !== (ROUNDS_F + ROUNDS_P) * T) {
  throw new Error(`C length ${C.length}, expected ${(ROUNDS_F + ROUNDS_P) * T}`);
}
if (M.length !== T || M.some((r) => r.length !== T)) {
  throw new Error("M is not t-by-t");
}

// Emit as a raw 32-byte big-endian array literal so the contract needs no
// hex-decoding dependency.
const bytes32 = (n) => {
  const h = n.toString(16).padStart(64, "0");
  const parts = [];
  for (let i = 0; i < 64; i += 2) parts.push(`0x${h.slice(i, i + 2)}`);
  return `[${parts.join(", ")}]`;
};

// Group the flat C array into one row of t constants per round.
const rounds = [];
for (let r = 0; r < ROUNDS_F + ROUNDS_P; r++) {
  rounds.push(C.slice(r * T, r * T + T));
}

// Test vectors: computed by circomlibjs itself, asserted in the Rust test.
const poseidon = await buildPoseidon();
const F = poseidon.F;
const h2 = (a, b) => F.toObject(poseidon([a, b]));
const VECTORS = [
  [0n, 0n],
  [1n, 2n],
  [
    21888242871839275222246405745257275088548364400416034343698204186575808495616n,
    123456789n,
  ],
  [7n, 0n],
];
const vectors = VECTORS.map(([a, b]) => ({ a, b, out: h2(a, b) }));

// Empty-subtree roots: zeros[i] is the root of an all-empty subtree of height i.
// Deterministic, so they are baked in as constants rather than recomputed.
// That keeps a Merkle insert down to LEVELS hashes with no setup cost.
const LEVELS = 20;
const zeros = [0n];
for (let i = 0; i < LEVELS; i++) zeros.push(h2(zeros[i], zeros[i]));

// Roots of a depth-LEVELS tree after each successive insert, computed with the
// same MerkleTree the prover uses. The contract's incremental tree must agree
// with these exactly, or an off-chain proof would not verify on-chain.
const { MerkleTree } = await import("./lib/veil.mjs");
const tree = new MerkleTree(LEVELS, h2);
const MERKLE_LEAVES = [1n, 2n, 3n, 4n, 5n];
const merkleRoots = MERKLE_LEAVES.map((leaf) => {
  tree.insert(leaf);
  return tree.root();
});

const rustArray = (vals, indent) =>
  vals.map((v) => `${indent}${bytes32(v)},`).join("\n");

const out = `// @generated by scripts/gen_poseidon_params.mjs. Do not edit by hand.
//
// circomlib Poseidon parameters over BN254 for t = 3 (the 2-input hash used at
// every Merkle node), together with test vectors produced by circomlibjs.
//
// Regenerate with:  node scripts/gen_poseidon_params.mjs

/// State size: 2 inputs plus the capacity element.
pub const T: u32 = ${T};
/// S-box degree (x^5).
pub const D: u32 = 5;
/// Full rounds.
pub const ROUNDS_F: u32 = ${ROUNDS_F};
/// Partial rounds (circomlib's table value for t = 3).
pub const ROUNDS_P: u32 = ${ROUNDS_P};

/// MDS matrix, row-major: \`state'[i] = sum_j MDS[i][j] * state[j]\`.
pub const MDS: [[[u8; 32]; ${T}]; ${T}] = [
${M.map(
  (row) => `    [
${rustArray(row, "        ")}
    ],`
).join("\n")}
];

/// Round constants, one row of \`T\` per round, \`ROUNDS_F + ROUNDS_P\` rows.
pub const ROUND_CONSTANTS: [[[u8; 32]; ${T}]; ${ROUNDS_F + ROUNDS_P}] = [
${rounds
  .map(
    (row) => `    [
${rustArray(row, "        ")}
    ],`
  )
  .join("\n")}
];

/// \`(a, b, poseidon2(a, b))\` triples computed by circomlibjs, used to prove the
/// on-chain permutation reproduces the circuit's hash exactly.
pub const TEST_VECTORS: [([u8; 32], [u8; 32], [u8; 32]); ${vectors.length}] = [
${vectors
  .map(
    (v) =>
      `    (\n        ${bytes32(v.a)},\n        ${bytes32(v.b)},\n        ${bytes32(
        v.out
      )},\n    ),`
  )
  .join("\n")}
];

/// Merkle tree depth. Matches \`Withdraw(levels)\` in circuits/withdraw.circom.
pub const LEVELS: u32 = ${LEVELS};

/// \`ZEROS[i]\` is the root of an all-empty subtree of height \`i\`, so \`ZEROS[0]\`
/// is the empty-leaf value and \`ZEROS[LEVELS]\` is the root of an empty tree.
pub const ZEROS: [[u8; 32]; ${zeros.length}] = [
${zeros.map((z) => `    ${bytes32(z)},`).join("\n")}
];

/// Leaves inserted one at a time, and the root the prover's tree holds after
/// each insert. The contract's incremental tree is checked against these.
pub const MERKLE_LEAVES: [[u8; 32]; ${MERKLE_LEAVES.length}] = [
${MERKLE_LEAVES.map((l) => `    ${bytes32(l)},`).join("\n")}
];
pub const MERKLE_ROOTS: [[u8; 32]; ${merkleRoots.length}] = [
${merkleRoots.map((r) => `    ${bytes32(r)},`).join("\n")}
];
`;

const path = "contracts/veil/src/poseidon_params.rs";
writeFileSync(path, out);
console.log(`wrote ${path}`);
console.log(`  t=${T} d=5 rounds_f=${ROUNDS_F} rounds_p=${ROUNDS_P}`);
console.log(`  ${rounds.length} rounds x ${T} constants, ${T}x${T} MDS`);
console.log(`  ${vectors.length} test vectors, e.g. poseidon(1,2) = ${vectors[1].out}`);
